In [7]:
import numpy as np

In [8]:
test = np.load('./full_model/extracted_params_full/conv.0.bias.npy')
print(test)

[-0.14363179  0.00375644 -0.08911841 -0.05254247 -0.02738671  0.0073457
  0.03110989  0.08017221  0.10829008  0.0535147   0.0009468  -0.08053993
 -0.01016417  0.00489326 -0.00335233  0.0008871   0.00362968 -0.0043742
  0.01495438 -0.02049801 -0.00726101  0.03550805 -0.04366403 -0.04395545
 -0.06755376 -0.02542621 -0.07183731  0.00067186 -0.01299273  0.01520601
 -0.25499278  0.04610612 -0.01797815 -0.03796871 -0.05280002 -0.07331632
 -0.04197202 -0.06667738 -0.0028838   0.04417436 -0.1884591   0.02489482
  0.04351369  0.07717176 -0.02380809 -0.02454805  0.09427566  0.01537322
  0.0111652  -0.07020866 -0.02802446  0.02206735 -0.07937008 -0.01168723
 -0.05477761 -0.0175094   0.06920609  0.00568075 -0.01892027  0.08548383
 -0.2448225  -0.04119298  0.0588397  -0.01047946]


In [9]:
image = np.asarray(range(32*32)).reshape((32, 32))
print(image)

[[   0    1    2 ...   29   30   31]
 [  32   33   34 ...   61   62   63]
 [  64   65   66 ...   93   94   95]
 ...
 [ 928  929  930 ...  957  958  959]
 [ 960  961  962 ...  989  990  991]
 [ 992  993  994 ... 1021 1022 1023]]


In [10]:
temp = np.load('./full_model/extracted_params_full/conv.0.weight.npy')
print(temp.shape)
print(temp[0][0][0])

(64, 3, 3, 3)
[-0.13165317 -0.26054558 -0.43336138]


In [11]:
def conv(filt, image):
    out = np.zeros((30, 30))
    for i in range(32 - 2):
        for j in range(32 - 2):
            s = 0
            s += filt[0][0] * image[i][j]
            s += filt[0][1] * image[i][j + 1]
            s += filt[0][2] * image[i][j + 2]
            s += filt[1][0] * image[i + 1][j]
            s += filt[1][1] * image[i + 1][j + 1]
            s += filt[1][2] * image[i + 1][j + 2]
            s += filt[2][0] * image[i + 2][j]
            s += filt[2][1] * image[i + 2][j + 1]
            s += filt[2][2] * image[i + 2][j + 2]
            out[i][j] = s
    return out

filt = np.ones((3, 3))
image = np.asarray(range(32*32)).reshape((32, 32))

def convPad(filt, image):
    out = np.zeros((32, 32))
    for i in range(34 - 2):
        for j in range(34 - 2):
            s = 0
            s += filt[0][0] * image[i][j]
            s += filt[0][1] * image[i][j + 1]
            s += filt[0][2] * image[i][j + 2]
            s += filt[1][0] * image[i + 1][j]
            s += filt[1][1] * image[i + 1][j + 1]
            s += filt[1][2] * image[i + 1][j + 2]
            s += filt[2][0] * image[i + 2][j]
            s += filt[2][1] * image[i + 2][j + 1]
            s += filt[2][2] * image[i + 2][j + 2]
            out[i][j] = s
    return out

In [12]:
print(conv(filt, image)*3)

[[  891.   918.   945.   972.   999.  1026.  1053.  1080.  1107.  1134.
   1161.  1188.  1215.  1242.  1269.  1296.  1323.  1350.  1377.  1404.
   1431.  1458.  1485.  1512.  1539.  1566.  1593.  1620.  1647.  1674.]
 [ 1755.  1782.  1809.  1836.  1863.  1890.  1917.  1944.  1971.  1998.
   2025.  2052.  2079.  2106.  2133.  2160.  2187.  2214.  2241.  2268.
   2295.  2322.  2349.  2376.  2403.  2430.  2457.  2484.  2511.  2538.]
 [ 2619.  2646.  2673.  2700.  2727.  2754.  2781.  2808.  2835.  2862.
   2889.  2916.  2943.  2970.  2997.  3024.  3051.  3078.  3105.  3132.
   3159.  3186.  3213.  3240.  3267.  3294.  3321.  3348.  3375.  3402.]
 [ 3483.  3510.  3537.  3564.  3591.  3618.  3645.  3672.  3699.  3726.
   3753.  3780.  3807.  3834.  3861.  3888.  3915.  3942.  3969.  3996.
   4023.  4050.  4077.  4104.  4131.  4158.  4185.  4212.  4239.  4266.]
 [ 4347.  4374.  4401.  4428.  4455.  4482.  4509.  4536.  4563.  4590.
   4617.  4644.  4671.  4698.  4725.  4752.  4779.  4806.  4

In [13]:
s = 0
s += image[29][29]
s += image[29][30]
s += image[29][31]
s += image[30][29]
s += image[30][30]
s += image[30][31]
s += image[31][29]
s += image[31][30]
s += image[31][31]
print(s*3)

26730


In [14]:
i = np.asarray(range(32*32), dtype=np.int32).reshape((32, 32))
j = np.zeros((34, 34))
j[1:33, 1:33] = i
print(j)

[[0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 1.000e+00 ... 3.000e+01 3.100e+01 0.000e+00]
 [0.000e+00 3.200e+01 3.300e+01 ... 6.200e+01 6.300e+01 0.000e+00]
 ...
 [0.000e+00 9.600e+02 9.610e+02 ... 9.900e+02 9.910e+02 0.000e+00]
 [0.000e+00 9.920e+02 9.930e+02 ... 1.022e+03 1.023e+03 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]]


In [17]:
out = convPad(filt, j)*3
for i in out:
    print(i)

[198. 306. 324. 342. 360. 378. 396. 414. 432. 450. 468. 486. 504. 522.
 540. 558. 576. 594. 612. 630. 648. 666. 684. 702. 720. 738. 756. 774.
 792. 810. 828. 558.]
[ 585.  891.  918.  945.  972.  999. 1026. 1053. 1080. 1107. 1134. 1161.
 1188. 1215. 1242. 1269. 1296. 1323. 1350. 1377. 1404. 1431. 1458. 1485.
 1512. 1539. 1566. 1593. 1620. 1647. 1674. 1125.]
[1161. 1755. 1782. 1809. 1836. 1863. 1890. 1917. 1944. 1971. 1998. 2025.
 2052. 2079. 2106. 2133. 2160. 2187. 2214. 2241. 2268. 2295. 2322. 2349.
 2376. 2403. 2430. 2457. 2484. 2511. 2538. 1701.]
[1737. 2619. 2646. 2673. 2700. 2727. 2754. 2781. 2808. 2835. 2862. 2889.
 2916. 2943. 2970. 2997. 3024. 3051. 3078. 3105. 3132. 3159. 3186. 3213.
 3240. 3267. 3294. 3321. 3348. 3375. 3402. 2277.]
[2313. 3483. 3510. 3537. 3564. 3591. 3618. 3645. 3672. 3699. 3726. 3753.
 3780. 3807. 3834. 3861. 3888. 3915. 3942. 3969. 3996. 4023. 4050. 4077.
 4104. 4131. 4158. 4185. 4212. 4239. 4266. 2853.]
[2889. 4347. 4374. 4401. 4428. 4455. 4482. 4509. 453